AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ApiArtifactBucketName:
    Type: String
Resources:
  WebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cowboycocktails3.com
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: WebsiteS3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${WebsiteS3Bucket}/*"
      Bucket: !Ref WebsiteS3Bucket

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub "${WebsiteS3Bucket}.s3-website.${AWS::Region}.amazonaws.com"
          Id: S3WebsiteOrigin
          CustomOriginConfig:
            HTTPPort: '80'
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        Comment: cowboycocktails3.com
        DefaultRootObject: index.html
        Aliases:
        - cowboycocktails3.com
        - www.cowboycocktails3.com
        DefaultCacheBehavior:
          TargetOriginId: S3WebsiteOrigin
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: all
        CustomErrorResponses:
        - ErrorCode: '404'
          ResponsePagePath: "/404.html"
          ResponseCode: '404'
          ErrorCachingMinTTL: '30'
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:537748127473:certificate/6d2fc569-a6a1-43f6-a9fd-588872fed017
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1

  ApiArtifactsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ApiArtifactBucketName

Outputs:
  CloudFrontId:
    Value: !GetAtt CloudFrontDistribution.Id
    Description: CloudFront Distribution ID
