AWSTemplateFormatVersion: 2010-09-09
Resources:
  WebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cowboycocktails3.com
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: WebsiteS3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${WebsiteS3Bucket}/*"
      Bucket: !Ref WebsiteS3Bucket

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub "${WebsiteS3Bucket}.s3-website.${AWS::Region}.amazonaws.com"
          Id: S3WebsiteOrigin
          CustomOriginConfig:
            HTTPPort: '80'
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        Comment: cowboycocktails3.com
        DefaultRootObject: index.html
        # Aliases:
        # - cowboycocktails3.com
        # - "*.cowboycocktails3.com"
        DefaultCacheBehavior:
          TargetOriginId: S3WebsiteOrigin
          # SmoothStreaming: 'false'
          # ForwardedValues:
          #   QueryString: 'false'
          #   Cookies:
          #     Forward: all
          # TrustedSigners:
          # - 1234567890EX
          # - 1234567891EX
          ViewerProtocolPolicy: allow-all
        CustomErrorResponses:
        - ErrorCode: '404'
          ResponsePagePath: "/404.html"
          ResponseCode: '404'
          ErrorCachingMinTTL: '30'
        PriceClass: PriceClass_200
        # Restrictions:
        #   GeoRestriction:
        #     RestrictionType: whitelist
        #     Locations:
        #     - AQ
        #     - CV
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteS3Bucket.WebsiteURL
    Description: URL for website hosted on S3
