name: Deploy CloudFormation Stacks and upload artifacts

# Controls when the action will run.
on:
  push:
    branches:
      - main

jobs:
  cfn-deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy s3_buckets CFN stack
        id: deploy-s3-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name:  cowboy-cocktails-s3-stack
          template: cfn/s3_buckets.yaml
          no-fail-on-empty-changeset: "1"
      - name: Upload website contents
        id: upload-website-contents
        run: aws s3 sync . \
          --exclude "*" \
          --include "index.html" \
          --include "assets"
          --include "images"
          s3://cowboycocktails3.com